"""date_edited added in Post table

Revision ID: 50d12c205cd7
Revises: b6ac8eac80d1
Create Date: 2023-01-02 04:15:53.575113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50d12c205cd7'
down_revision = 'b6ac8eac80d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_edited', sa.DateTime(), nullable=True))
        batch_op.drop_column('edited_timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited_timestamp', sa.DATETIME(), nullable=True))
        batch_op.drop_column('date_edited')

    # ### end Alembic commands ###
