"""added optional attributes to post

Revision ID: e7a77359df3e
Revises: 47665ac445d8
Create Date: 2022-12-28 22:36:19.668276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a77359df3e'
down_revision = '47665ac445d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('is_archived')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
